import { useState, useEffect, useMemo } from 'react';
import { motion } from 'framer-motion';
import { Download, Users, BookOpen, IndianRupee, History, Calendar, Wallet } from 'lucide-react';
import AnimatedCard from '../../components/AnimatedCard';
import { useAuth } from '../../context/AuthContext';
import api from '../../services/api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
  Filler,
} from 'chart.js';
import { Bar, Doughnut } from 'react-chartjs-2';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  BarElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
  Filler
);

const Reports = () => {
  const { user } = useAuth();
  
  const [rawData, setRawData] = useState({
    users: [], books: [], issues: [], fines: [], defaultStats: null
  });
  
  const [dates, setDates] = useState({ startDate: '', endDate: '' });
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchAllData = async () => {
      try {
        const [statsRes, usersRes, booksRes, issuesRes, finesRes] = await Promise.all([
           api.get('/dashboard/stats'),
           api.get('/users'),
           api.get('/books'),
           api.get('/issues'),
           api.get('/fines').catch(() => ({ data: [] })) 
        ]);

        setRawData({
           defaultStats: statsRes.data,
           users: usersRes.data,
           books: booksRes.data,
           issues: issuesRes.data,
           fines: finesRes.data
        });
      } catch (error) {
        console.error("Failed to fetch report data", error);
      } finally {
        setIsLoading(false);
      }
    };
    fetchAllData();
  }, []);

  const data = useMemo(() => {
    if (!rawData.defaultStats) return null;

    const isWithinRange = (item) => {
      if (!dates.startDate && !dates.endDate) return true;
      
      const dateStr = item.createdAt || item.created_at || item.issue_date || item.issueDate || item.date;
      if (!dateStr) return false; 

      const itemDate = new Date(dateStr);
      const start = dates.startDate ? new Date(dates.startDate) : new Date('2000-01-01');
      const end = dates.endDate ? new Date(dates.endDate) : new Date('2100-01-01');
      end.setHours(23, 59, 59, 999); 

      return itemDate >= start && itemDate <= end;
    };

    const filteredUsers = rawData.users.filter(isWithinRange);
    const filteredBooks = rawData.books.filter(isWithinRange);
    const filteredIssues = rawData.issues.filter(isWithinRange);
    const filteredFines = rawData.fines.filter(isWithinRange);

    const roles = filteredUsers.reduce((acc, curr) => {
       acc[curr.role] = (acc[curr.role] || 0) + 1;
       return acc;
    }, {});

    const categories = filteredBooks.reduce((acc, curr) => {
       const cat = curr.category || 'Uncategorized';
       acc[cat] = (acc[cat] || 0) + 1;
       return acc;
    }, {});

    // FIX: Bulletproof Fine Calculation Logic
    let calculatedPending = 0;
    let calculatedCollected = 0;

    filteredFines.forEach(f => {
       // Safely convert string amounts to numbers
       const amt = Number(f.amount || 0);
       // Force status to lowercase so "Paid", "PAID", or "paid" all match perfectly
       const status = String(f.status || '').toLowerCase().trim();

       if (status === 'paid' || status === 'collected') {
           calculatedCollected += amt;
       } else if (status === 'pending' || status === 'unpaid') {
           calculatedPending += amt;
       }
    });

    const isFiltering = dates.startDate || dates.endDate;
    const stats = isFiltering ? {
      totalUsers: filteredUsers.length,
      totalBooks: filteredBooks.length,
      totalIssued: filteredIssues.length,
    } : rawData.defaultStats;

    return {
       stats,
       usersRoleDist: [
         (roles['Admin'] || 0) + (roles['Librarian'] || 0), 
         roles['Student'] || 0,
         roles['Professor'] || 0
       ],
       booksCatDist: {
         labels: Object.keys(categories),
         data: Object.values(categories)
       },
       finesPending: calculatedPending,
       finesCollected: calculatedCollected 
    };
  }, [rawData, dates]);

  const generateSystemReportPDF = () => {
    if (!data) return;
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.setTextColor(30, 41, 59);
    doc.text("LibOrbit Official", 14, 20);

    doc.setFontSize(14);
    doc.setTextColor(79, 70, 229);
    doc.text("System Analytics & Summary Report", 14, 30);

    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by: ${user?.name || 'Administrator'}`, 14, 38);
    
    const dateRangeText = (dates.startDate || dates.endDate) 
        ? `Reporting Period: ${dates.startDate || 'Beginning'} to ${dates.endDate || 'Present'}` 
        : `Reporting Period: All Time`;
    doc.text(dateRangeText, 14, 44);
    doc.text(`Export Date: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 14, 50);

    doc.setFontSize(12);
    doc.setTextColor(30, 41, 59);
    doc.text("1. Overall System Summary", 14, 62);

    autoTable(doc, {
      startY: 67,
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' },
      body: [
        ['Total Books Added', data.stats.totalBooks.toString()],
        ['Total Accounts Registered', data.stats.totalUsers.toString()],
        ['Total Books Issued', data.stats.totalIssued.toString()],
        ['Total Fines Collected (Paid)', `Rs. ${data.finesCollected}`],
        ['Total Pending Fines (Unpaid)', `Rs. ${data.finesPending}`]
      ],
      styles: { fontSize: 10, cellPadding: 4 },
      alternateRowStyles: { fillColor: [248, 250, 252] }
    });

    let currentY = doc.lastAutoTable.finalY + 15;
    doc.text("2. User Role Distribution", 14, currentY);

    autoTable(doc, {
      startY: currentY + 5,
      theme: 'grid',
      head: [['User Role Category', 'Total Accounts']],
      headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' },
      body: [
        ['Staff (Admins & Librarians)', data.usersRoleDist[0].toString()],
        ['Students', data.usersRoleDist[1].toString()],
        ['Professors', data.usersRoleDist[2].toString()]
      ],
      styles: { fontSize: 10, cellPadding: 4 },
      alternateRowStyles: { fillColor: [248, 250, 252] }
    });

    currentY = doc.lastAutoTable.finalY + 15;
    if (currentY > 230) { doc.addPage(); currentY = 20; }
    doc.text("3. Catalog Inventory by Category", 14, currentY);

    const categoryRows = data.booksCatDist.labels.map((label, index) => [
      label, data.booksCatDist.data[index].toString()
    ]);

    autoTable(doc, {
      startY: currentY + 5,
      theme: 'grid',
      head: [['Book Category', 'Number of Titles']],
      headStyles: { fillColor: [79, 70, 229], textColor: 255, fontStyle: 'bold' },
      body: categoryRows.length > 0 ? categoryRows : [['No books in this date range', '0']],
      styles: { fontSize: 10, cellPadding: 4 },
      alternateRowStyles: { fillColor: [248, 250, 252] }
    });

    doc.save(`Liborbit_System_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const containerVariants = { hidden: { opacity: 0 }, visible: { opacity: 1, transition: { staggerChildren: 0.1 } } };
  const itemVariants = { hidden: { opacity: 0, y: 20 }, visible: { opacity: 1, y: 0, transition: { type: 'spring', stiffness: 300, damping: 24 } } };

  if (isLoading || !data) {
     return (
       <div className="space-y-6">
          <div className="h-24 bg-slate-100 animate-pulse rounded-2xl"></div>
          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-6">
             {[...Array(5)].map((_, i) => <div key={i} className="h-32 bg-slate-100 animate-pulse rounded-2xl"></div>)}
          </div>
       </div>
     );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4 pb-4 border-b border-slate-200">
        <div>
          <h1 className="text-4xl font-display font-bold text-slate-800 tracking-tight mb-2">
            System Reports
          </h1>
          <p className="text-slate-500 font-medium">
            Analyze library performance over any time period.
          </p>
        </div>
        <button 
          onClick={generateSystemReportPDF}
          className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white px-5 py-3 rounded-xl font-bold shadow-sm transition-all shrink-0"
        >
          <Download size={20} /> Export Report (PDF)
        </button>
      </div>

      <AnimatedCard className="p-4 border-slate-200 shadow-sm bg-white">
        <div className="flex flex-col md:flex-row gap-4 items-end">
           <div className="flex flex-1 items-center gap-3">
              <div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center text-slate-500 shrink-0">
                 <Calendar size={18} />
              </div>
              <div className="w-full">
                <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">From Date</label>
                <input 
                  type="date" 
                  value={dates.startDate}
                  onChange={(e) => setDates({...dates, startDate: e.target.value})}
                  className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-indigo-500 transition-colors text-slate-700 font-medium cursor-pointer"
                />
              </div>
           </div>
           <div className="w-full flex-1">
              <label className="block text-xs font-bold text-slate-500 uppercase tracking-wider mb-1">To Date</label>
              <input 
                type="date" 
                value={dates.endDate}
                min={dates.startDate} 
                onChange={(e) => setDates({...dates, endDate: e.target.value})}
                className="w-full p-2.5 bg-slate-50 border border-slate-200 rounded-xl outline-none focus:border-indigo-500 transition-colors text-slate-700 font-medium cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                disabled={!dates.startDate}
              />
           </div>
           {(dates.startDate || dates.endDate) && (
               <button 
                 onClick={() => setDates({startDate: '', endDate: ''})}
                 className="px-5 py-2.5 bg-rose-50 text-rose-600 hover:bg-rose-100 rounded-xl font-bold transition-colors border border-rose-100 shrink-0 w-full md:w-auto"
               >
                 Clear Filter
               </button>
           )}
        </div>
      </AnimatedCard>

      <motion.div variants={containerVariants} initial="hidden" animate="visible" className="space-y-6">
         <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-6">
            <AnimatedCard variants={itemVariants} className="p-5 border-slate-200 shadow-sm flex items-center gap-4 bg-white">
               <div className="w-12 h-12 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center shrink-0">
                  <BookOpen size={24} />
               </div>
               <div>
                  <div className="text-xs font-bold text-slate-500 uppercase tracking-wide mb-1">Books Added</div>
                  <div className="text-2xl font-display font-bold text-slate-800">{data.stats.totalBooks}</div>
               </div>
            </AnimatedCard>

            <AnimatedCard variants={itemVariants} className="p-5 border-slate-200 shadow-sm flex items-center gap-4 bg-white">
               <div className="w-12 h-12 rounded-xl bg-sky-50 text-sky-600 flex items-center justify-center shrink-0">
                  <Users size={24} />
               </div>
               <div>
                  <div className="text-xs font-bold text-slate-500 uppercase tracking-wide mb-1">Users Joined</div>
                  <div className="text-2xl font-display font-bold text-slate-800">{data.stats.totalUsers}</div>
               </div>
            </AnimatedCard>

            <AnimatedCard variants={itemVariants} className="p-5 border-slate-200 shadow-sm flex items-center gap-4 bg-white">
               <div className="w-12 h-12 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center shrink-0">
                  <History size={24} />
               </div>
               <div>
                  <div className="text-xs font-bold text-slate-500 uppercase tracking-wide mb-1">Books Issued</div>
                  <div className="text-2xl font-display font-bold text-slate-800">{data.stats.totalIssued}</div>
               </div>
            </AnimatedCard>

            <AnimatedCard variants={itemVariants} className="p-5 border-emerald-100 shadow-sm flex items-center gap-4 bg-emerald-50/30">
               <div className="w-12 h-12 rounded-xl bg-emerald-100 text-emerald-600 flex items-center justify-center shrink-0">
                  <Wallet size={24} />
               </div>
               <div>
                  <div className="text-xs font-bold text-emerald-700 uppercase tracking-wide mb-1">Collected Fines</div>
                  <div className="text-2xl font-display font-bold text-emerald-800">₹{data.finesCollected}</div>
               </div>
            </AnimatedCard>

            <AnimatedCard variants={itemVariants} className="p-5 border-rose-100 shadow-sm flex items-center gap-4 bg-rose-50/30">
               <div className="w-12 h-12 rounded-xl bg-rose-100 text-rose-600 flex items-center justify-center shrink-0">
                  <IndianRupee size={24} />
               </div>
               <div>
                  <div className="text-xs font-bold text-rose-700 uppercase tracking-wide mb-1">Pending Fines</div>
                  <div className="text-2xl font-display font-bold text-rose-800">₹{data.finesPending}</div>
               </div>
            </AnimatedCard>
         </div>

         <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <AnimatedCard variants={itemVariants} className="p-6 border-slate-200 shadow-sm flex flex-col items-center bg-white">
               <h3 className="text-xl font-display font-semibold text-slate-800 mb-6 self-start">User Demographics (Period)</h3>
               <div className="w-full max-w-[300px] aspect-square flex items-center justify-center pb-4">
                 <Doughnut 
                    data={{
                      labels: ['Staff', 'Students', 'Professors'],
                      datasets: [{ data: data.usersRoleDist, backgroundColor: ['#f43f5e', '#6366f1', '#0ea5e9'], borderWidth: 0 }]
                    }} 
                    options={{ responsive: true, maintainAspectRatio: false }}
                 />
               </div>
            </AnimatedCard>

            <AnimatedCard variants={itemVariants} className="p-6 border-slate-200 shadow-sm flex flex-col bg-white">
               <h3 className="text-xl font-display font-semibold text-slate-800 mb-6">Catalog Additions by Category</h3>
               <div className="w-full h-[300px] flex-1">
                 <Bar 
                    data={{
                       labels: data.booksCatDist.labels.length > 0 ? data.booksCatDist.labels : ['No Data'],
                       datasets: [{
                          label: 'Books Added',
                          data: data.booksCatDist.data.length > 0 ? data.booksCatDist.data : [0],
                          backgroundColor: 'rgba(99, 102, 241, 0.8)',
                          borderRadius: 4
                       }]
                    }}
                    options={{ responsive: true, maintainAspectRatio: false, plugins: { legend: { display: false } } }}
                 />
               </div>
            </AnimatedCard>
         </div>
      </motion.div>
    </div>
  );
};

export default Reports;